// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzbefujblukuhsgppcat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6YmVmdWpibHVrdWhzZ3BwY2F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczOTg2NTYsImV4cCI6MjA3Mjk3NDY1Nn0.ghutE1CK2lftMhwUQV2fix2BELBbrUGUpG-VRqWA3mk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});